### PR TITLE
Fix misc UI issues on sources

### LINKED ISSUE #37: Fix bugs on data visualization in Sources Manager

### PR DESCRIPTION
**Pull request by m453h**
This PR includes several changes to improve the user interface of the `sources` application. The following changes have been implemented:

### 1. Updates to `SourcesAppMenu` component:
Remove `Browse Geographic Collections` menu item (which renders a page with not content) and rename the `Browse Other Collections` to `Browse Collections`

**Before:**
Screenshot 2025-02-11 at 13 37 49

**After:**
Screenshot 2025-02-11 at 13 38 03

### 2. Remove CollectionMetadataCoverageSummaryContainer:
Remove `CollectionMetadataCoverageSummaryContainer` which does not display any meaningful information.

**Before**
Screenshot 2025-02-11 at 13 47 22

**After**
Screenshot 2025-02-11 at 13 48 55

### 3. Fix Issues on Data Card Component :
Fix the issue of an invalid date string displaying on the 'Covered Since' card when viewing details about a source. Additionally, ensure that cards are only rendered when there is actual data, preventing unnecessary cards from being shown with no meaningful information.
**Before**
Screenshot 2025-02-11 at 13 55 46

**After**
Screenshot 2025-02-11 at 13 50 40

Fixes #37

### CODE REVIEW

File: src/components/common/statbar/Stat.js [hunk 1]
```diff
@@ -31,9 +31,11 @@ class Stat extends React.Component {
...
     return (
-      <DataCard className="stat">
-        {contentToShow}
-      </DataCard>
+      data !== '?' && (
+        <DataCard className="stat">
+          {contentToShow}
+        </DataCard>
+      )
     );
```
Comment (kilemensi) [inline src/components/common/statbar/Stat.js:39]: Why not
```jsx
    if (!(data !== '?')) {
      return null;
    }
    return (
      <DataCard className="stat">
        {contentToShow}
      </DataCard>
    );
```

? And not sure why we're concerned with `data` instead of `contentToShow` either.

File: src/components/source/mediaSource/SourceStatInfo.js [hunk 2]
```diff
@@ -26,7 +26,7 @@ const SourceStatInfo = (props) => {
   }
   let formattedDateStr;
   if (sourceInfo.start_date) {
-    const startDate = healthStartDateToMoment(sourceInfo.start_date);
+    const startDate = healthStartDateToMoment(sourceInfo.start_date, false);
```
Comment (kilemensi) [inline src/components/source/mediaSource/SourceStatInfo.js:29]: What does `false` imply here?

**Review by kilemensi — APPROVED** [review]
🚀 (LGTM but I don't have full contenxt)

---

1. Can we add RESEARCH to the main menu (after MEDIA DATA)
2. On data card, I think some of the cards are longer than others
411933674-3edf8e9f-0819-4aab-a3fd-775cd9a6c8fd

File: src/components/common/statbar/Stat.js (hunk 1 above)
Comment (m453h) [reply src/components/common/statbar/Stat.js:39]: Sure the suggestion you made works better, we can easily remove the condition if we ever need to.

Regarding the check on `data` from the tests i did when we render the `Stat` component it appears `contentToShow` is always assigned to a react component, thus it made more sense to check on the value of data (which will have `?` or some other value that will be displayed)
